name: Build CompatNoCheatPlus

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: 21
          distribution: temurin

      - name: Build CompatNoCheatPlus
        run: mvn clean package

      - name: Release CompatNoCheatPlus
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "CompatNoCheatPlus"
          automatic_release_tag: "cncp"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "target/*.jar"
          prerelease: true
